### ISSUE TITLE
Login with Password fails with actual Labor-Version 07.24-84940 BETA

### ISSUE THREAD

**Issue by waywit** [oe73773/fritzbox-munin#5]
Hi oe73773

I am using your fork of the FritzBox-munin Plugin and it is working great... I actually using the labor version of FritzOS  07.24-84940 BETA and the Login screen has changed, in the new version there will be th possibility to login using the FritzBox users, but also with the "old" password. But the Login without password is mapped to a automatically created user "Fritz666", so this one will be used to to login without any user. If I login without a Username, the logging states that Fritz666 has logged in.

Logfile:

> 2020/12/28-09:25:07 [305158] Error output from fritzbox_fritz.box_wifi_devices:
> 2020/12/28-09:25:07 [305158] 	Couldn't retrieve connected fritzbox wifi devices
> 2020/12/28-09:25:07 [305158] Service 'fritzbox_fritz.box_wifi_devices' exited with status 1/0.
> 2020/12/28-09:25:08 [305158] Error output from fritzbox_fritz.box_uptime:
> 2020/12/28-09:25:08 [305158] 	Couldn't retrieve fritzbox uptime
> 2020/12/28-09:25:08 [305158] Service 'fritzbox_fritz.box_uptime' exited with status 1/0.
> 2020/12/28-09:25:10 [305158] Error output from fritzbox_fritz.box_cpu_usage:
> 2020/12/28-09:25:10 [305158] 	Couldn't retrieve fritzbox cpu usage
> 2020/12/28-09:25:10 [305158] Service 'fritzbox_fritz.box_cpu_usage' exited with status 1/0.
> 2020/12/28-09:25:10 [305158] Error output from fritzbox_fritz.box_power_consumption:
> 2020/12/28-09:25:10 [305158] 	Couldn't retrieve fritzbox power consumption
> 2020/12/28-09:25:10 [305158] Service 'fritzbox_fritz.box_power_consumption' exited with status 1/0.
> 2020/12/28-09:25:11 [305158] Error output from fritzbox_fritz.box_memory_usage:
> 2020/12/28-09:25:11 [305158] 	Couldn't retrieve fritzbox memory usage
> 2020/12/28-09:25:11 [305158] Service 'fritzbox_fritz.box_memory_usage' exited with status 1/0.

I have attached some screenshots to this issue... Old Style Login mask (see Link):
<img width="473" alt="Old-Style Login" src="https://user-images.githubusercontent.com/8435459/103200496-c7b66300-48ed-11eb-9d42-ea086e9d2fca.png">

User Login (internal)
<img width="472" alt="Login with User" src="https://user-images.githubusercontent.com/8435459/103200532-e157aa80-48ed-11eb-99d8-ed54b2db56ff.png">

User Select-List:
<img width="474" alt="User List on Login" src="https://user-images.githubusercontent.com/8435459/103200550-ec123f80-48ed-11eb-825a-1becda157a23.png">

All fritzconnection based stats are still okay, but the following are getting a wrong password message:
- Connected WLAN Clients
- CPU temperature
- CPU usage
- Memory
- Power Consumption
- Uptime

Perhaps the login in future need to provide an additional username to login? 

If I may can help you fix this issue, do not hesitate to ask :-)

**Comment by oe73773** [comment]
Hi,

I finally managed to create a code that works with Fritz!OS 7.24 and above.
I tested with a Fritz!Box 7490 Version 7.12 and Fritz!Box 7580 Version 7.25.

The new version requires python3
